// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/alkuinvito/ai-assistant/internal/auth"
	"github.com/alkuinvito/ai-assistant/internal/middlewares"
	"github.com/alkuinvito/ai-assistant/internal/routers"
	"github.com/alkuinvito/ai-assistant/internal/users"
	"github.com/alkuinvito/ai-assistant/pkg/cache"
	"github.com/alkuinvito/ai-assistant/pkg/database"
	"github.com/alkuinvito/ai-assistant/pkg/mailer"
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func NewHttpServer(log *logrus.Logger) (*fiber.App, func(), error) {
	middleware := middlewares.NewMiddleware(log)
	db, cleanup, err := database.NewDatabase(log)
	if err != nil {
		return nil, nil, err
	}
	userRepository := users.NewUserRepository()
	userService := users.NewUserService(db, userRepository)
	userHandler := users.NewUserHandler(userService)
	userRouter := users.NewUserRouter(userHandler)
	cacheCache, cleanup2 := cache.NewRedisCache(log)
	mailerMailer, cleanup3 := mailer.NewSmtpMail(log)
	authService := auth.NewAuthService(cacheCache, db, mailerMailer, userService)
	authHandler := auth.NewAuthHandler(authService)
	authRouter := auth.NewAuthRouter(authHandler)
	router := routers.NewRouter(log, middleware, userRouter, authRouter)
	app := NewApp(router)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var authSet = wire.NewSet(auth.NewAuthRouter, auth.NewAuthHandler, auth.NewAuthService)

var userSet = wire.NewSet(users.NewUserRepository, users.NewUserService, users.NewUserHandler, users.NewUserRouter)
